package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.FileChooser;

public class FaddworkController implements Initializable
{
	@FXML
	private TextField worknameField;
	@FXML
	private Label classcodeLbl;
	@FXML
	private Label workidLbl;
	@FXML
	private Label fidLbl;
	@FXML
	private Button submitbtn;

	@FXML
	private Label submitLbl;

	@FXML
	private Label pathLbl;

	String workid, path;

	public Button get(String classcode, String fid, Stage stage)
	{
		//classcodeLbl.setStyle("-fx-background-color: white;");
		classcodeLbl.setText(classcode);
		
		//fidLbl.setStyle("-fx-background-color: white;");
		fidLbl.setText(fid);
		

		FileChooser chooser = new FileChooser();
		Button choose = new Button("Choose File");

		choose.setOnAction(e -> {
			File selected = chooser.showOpenDialog(stage);
			// sfilelbl.setText(selected.getAbsolutePath());
			path = selected.getAbsolutePath();
			pathLbl.setText(path);
			//pathLbl.setStyle("-fx-background-color: white;");
			
		});

		// VBox vbx =new VBox() ;
		// vbx.getChildren().add(choose) ;

		return (choose);

	}

	// Event Listener on Button[#submitbtn].onAction
	@FXML
	public void submitAction(ActionEvent event)
	{
		// TODO Autogenerated

		String workname = worknameField.getText();
		String classcode = classcodeLbl.getText();
		String fid = fidLbl.getText();
		try
		{
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/classroom", "root", "");
			PreparedStatement ps1 = con
					.prepareStatement("select * from fdashboard where fid=? and classcode = ? and workid = ?");
			ps1.setString(1, fid);
			ps1.setString(2, classcode);
			ps1.setString(3, workid);
			ResultSet res1 = ps1.executeQuery();
			if (res1.next())
			{
				PreparedStatement ps3 = con.prepareStatement(
						"Update fdashboard set ffile = LOAD_FILE(?) , workname = ? where fid = ? and classcode = ? and workid = ?");
				ps3.setString(1, path);
				ps3.setString(2, workname);
				ps3.setString(3, fid);
				ps3.setString(4, classcode);
				ps3.setString(5, workid);
				ps3.executeUpdate();
				submitLbl.setText("Update Success");
			} else
			{
				PreparedStatement ps3 = con
						.prepareStatement("Insert into fdashboard values (?, LOAD_FILE(?), ?, ? , ?)");

				ps3.setString(1, fid);
				ps3.setString(2, path);
				ps3.setString(3, classcode);
				ps3.setString(4, workid);
				ps3.setString(5, workname);
				// ps3.setInt(6, 1);
				ps3.executeUpdate();
				submitLbl.setText("Upload Success");

			}
		} catch (Exception ex)
		{
			ex.printStackTrace();
		}

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1)
	{
		// TODO Auto-generated method stub
		workid = RandomString.getAlphaNumericString(4);
		workidLbl.setText(workid);

	}
}
